### ISSUE TITLE
Add the ocial project to the repository

### ISSUE THREAD

**Issue by kasimbozdag** [kasimbozdag/swe_574#10]
Add the ocial project to the repository
This project will be build upon a project that has been done in SWE 573
we decided to use the ocial Project belonging to @onurasiliskender 
the project will be forked and copied to the this project

**Comment by kasimbozdag** [comment]
the project has been added and it has been tested in a local environment

**Comment by mdo91** [comment]
I have cloned this project into my local environment. However, the sections regarding enrolling in a learning path is not available. 
![Screen Shot 2019-10-20 at 4 05 15 PM](https://user-images.githubusercontent.com/10821064/67159686-e36cc380-f350-11e9-8226-9d22f8b6cf28.png)

**Comment by onurasiliskender** [comment]
@mdo91 hic olusturulmus bir course var mi? Senin databasein bos olabilir. Learning path ya da sectionlar bakmaya calistigin sayfada gozuken seyler degiller cunku, neye bakmaya calistigini anlamadim.

**Comment by mdo91** [comment]
Actually I have created a course in my local database, after I have published it, I registered as another user to view the course and yet it is not available to be enrolled in.However, i will have a look into your user guide. 

![Screen Shot 2019-10-20 at 7 30 43 PM](https://user-images.githubusercontent.com/10821064/67162558-b7ac0680-f36d-11e9-82c1-c7b8c5abc587.png)

**Comment by onurasiliskender** [comment]
@mdo91 Have you clicked "Publish" button? It only appears when all sections have green tick. In the picture you have uploaded; there is no publish button.
